apiVersion: v1 
kind: ServiceAccount
metadata:
  name: cart
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::934235628328:role/ssm-for-eks

---

apiVersion: v1
kind: Pod
metadata:
  name: cart
  labels:
    component: cart
spec:
  containers:
    - name: cart
      image: 934235628328.dkr.ecr.us-east-1.amazonaws.com/cart:v14.0.2
      volumeMounts:
        - mountPath: /params
          name: params
  initContainers:
    - name: aws-ssm-param-storet
      image: 934235628328.dkr.ecr.us-east-1.amazonaws.com/aws-ssm-param-store:v1.0.2
      args: ["User:dev.docdb.user", "REDIS_HOST:dev..elasticache.endpoint", "CATALOGUE_HOST:dev.cart.catalogue_host", "CATALOGUE_PORT:dev.cart.catalogue_port" ]
      volumeMounts:
        - mountPath: /params
          name: params
  volumes:
    - name: params
      emptyDir:
        sizeLimit: 100Mi

---
apiVersion: v1
kind: Service
metadata:
  name: cart
spec: 
  selector:
    component: cart
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
