apiVersion: v1
kind: Pod
metadata:
  name: cart
  labels:
    component: cart
spec:
  containers:
    - name: cart
      image: 934235628328.dkr.ecr.us-east-1.amazonaws.com/cart:v1.0.2


---
apiVersion: v1
kind: Service
metadata:
  name: cart
spec: 
  selector:
    component: cart
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080