apiVersion: v1 
kind: ServiceAccount
metadata:
  name: cart
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::934235628328:role/ssm-for-eks
spec:
  ServiceAccountName: cart

---

apiVersion: v1
kind: Pod
metadata:
  name: cart
  labels:
    component: cart
spec:
  ServiceAccountName: cart
  containers:
    - name: cart
      image: 934235628328.dkr.ecr.us-east-1.amazonaws.com/cart:v1.0.2
  initcontainers:
    - name: cart
      image: 934235628328.dkr.ecr.us-east-1.amazonaws.com/aws-ssm-params-store:v1.0.2
      args: ["sample: dev.doddb.pass"]


---
apiVersion: v1
kind: Service
metadata:
  name: cart
spec: 
  selector:
    component: cart
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
