apiVersion: v1
kind: Pod
metadata:
  name: catalogue
  labels:
    component: catalogue
spec:
  containers:
    - name: catalogue
      image: 934235628328.dkr.ecr.us-east-1.amazonaws.com/catalogue:v1.0.2


---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
spec: 
  selector:
    component: catalogue
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080