apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    component: frontend
spec:
  containers:
    - name: frontend
      image: 934235628328.dkr.ecr.us-east-1.amazonaws.com/frontend:v1.0.2
  

---
apiVersion: v1
kind: Service
metadata:
  name: forntend
spec: 
  type: LoadBalancer
  selector:
    component: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80