apiVersion: v1
kind: Pod
metadata:
  name: payment
  labels:
    component: payment
spec:
  containers:
    - name: payment
      image: 934235628328.dkr.ecr.us-east-1.amazonaws.com/payment:v1.0.2
  

---
apiVersion: v1
kind: Service
metadata:
  name: payment
spec: 
  selector:
    component: payment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080