apiVersion: v1
kind: Pod
metadata:
  name: shipping
  labels:
    component: shipping
spec:
  containers:
    - name: shipping
      image: 934235628328.dkr.ecr.us-east-1.amazonaws.com/shipping:v1.0.2
  

---
apiVersion: v1
kind: Service
metadata:
  name: shipping
spec: 
  selector:
    component: shipping
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080