apiVersion: v1
kind: Pod
metadata:
  name: user
  labels:
    component: user
spec:
  containers:
    - name: user
      image: 934235628328.dkr.ecr.us-east-1.amazonaws.com/user:v1.0.2
  

---
apiVersion: v1
kind: Service
metadata:
  name: user
spec: 
  selector:
    component: user
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080